name: Build & publish eXo CI images
on:
  schedule:
    - cron:  '0 22 * * 5' # Every Friday at 10 PM UTC
  workflow_dispatch:

jobs:
  build-base-images:
    name: "Build Base Images"
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageTag: base
            context: base
          - imageTag: base-alpine
            context: base-alpine
          - imageTag: base-ubuntu20
            context: base-ubuntu20
          - imageTag: base-ubuntu22
            context: base-ubuntu22
    uses: exoplatform/swf-scripts/.github/workflows/buildDockerImage.yml@master
    with:
      dockerImage: "exoplatform/ci"
      dockerImageTag: ${{ matrix.imageTag }}
      dockerFileContext: ${{ matrix.context }}
      signImage: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
      DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
      DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

  build-jdk-images:
    name: "Build JDK Images"
    needs: build-base-images
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageTag: jdk6
            context: jdk/jdk6
          - imageTag: jdk7
            context: jdk/jdk7
          - imageTag: jdk8
            context: jdk/jdk8
          - imageTag: jdk11
            context: jdk/jdk11
          - imageTag: jdk17
            context: jdk/jdk17
          - imageTag: jdk17-alpine
            context: jdk/jdk17-alpine
          - imageTag: jdk17-ubuntu20
            context: jdk/jdk17-ubuntu20
          - imageTag: jdk17-ubuntu22
            context: jdk/jdk17-ubuntu22
          - imageTag: jdk21-ubuntu20
            context: jdk/jdk21-ubuntu20
          - imageTag: jdk21-ubuntu22
            context: jdk/jdk21-ubuntu22
    uses: exoplatform/swf-scripts/.github/workflows/buildDockerImage.yml@master
    with:
      dockerImage: "exoplatform/ci"
      dockerImageTag: ${{ matrix.imageTag }}
      dockerFileContext: ${{ matrix.context }}
      signImage: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
      DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
      DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

  build-maven-images:
    name: "Build Maven Images"
    needs: build-jdk-images
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageTag: jdk6-maven30
            context: maven/jdk6-maven30
          - imageTag: jdk6-maven32
            context: maven/jdk6-maven32
          - imageTag: jdk7-maven30
            context: maven/jdk7-maven30
          - imageTag: jdk7-maven32
            context: maven/jdk7-maven32
          - imageTag: jdk8-maven30
            context: maven/jdk8-maven30
          - imageTag: jdk8-maven32
            context: maven/jdk8-maven32
          - imageTag: jdk8-maven33
            context: maven/jdk8-maven33
          - imageTag: jdk8-maven35
            context: maven/jdk8-maven35
          - imageTag: jdk11-maven33
            context: maven/jdk11-maven33
          - imageTag: jdk11-maven35
            context: maven/jdk11-maven35
          - imageTag: jdk11-maven36
            context: maven/jdk11-maven36
          - imageTag: jdk11-maven38
            context: maven/jdk11-maven38
          - imageTag: jdk17-maven36
            context: maven/jdk17-maven36
          - imageTag: jdk17-maven38
            context: maven/jdk17-maven38
          - imageTag: jdk17-maven39
            context: maven/jdk17-maven39
          - imageTag: jdk17-maven39-alpine
            context: maven/jdk17-maven39-alpine
          - imageTag: jdk17-maven39-ubuntu20
            context: maven/jdk17-maven39-ubuntu20
          - imageTag: jdk17-maven39-ubuntu22
            context: maven/jdk17-maven39-ubuntu22
          - imageTag: jdk17-maven40-ubuntu22
            context: maven/jdk17-maven40-ubuntu22
          - imageTag: jdk21-maven39-ubuntu20
            context: maven/jdk21-maven39-ubuntu20
          - imageTag: jdk21-maven39-ubuntu20
            context: maven/jdk21-maven39-ubuntu20
          - imageTag: jdk21-maven39-ubuntu22
            context: maven/jdk21-maven39-ubuntu22
          - imageTag: jdk21-maven40-ubuntu22
            context: maven/jdk21-maven40-ubuntu22
    
    uses: exoplatform/swf-scripts/.github/workflows/buildDockerImage.yml@master
    with:
      dockerImage: "exoplatform/ci"
      dockerImageTag: ${{ matrix.imageTag }}
      dockerFileContext: ${{ matrix.context }}
      signImage: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
      DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
      DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

  build-gradle-images:
    name: "Build Gradle Images"
    needs: build-jdk-images
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageTag: jdk8-gradle4
            context: gradle/jdk8-gradle4
          - imageTag: jdk8-gradle6
            context: gradle/jdk8-gradle6
          - imageTag: jdk17-gradle8
            context: gradle/jdk17-gradle8
    
    uses: exoplatform/swf-scripts/.github/workflows/buildDockerImage.yml@master
    with:
      dockerImage: "exoplatform/ci"
      dockerImageTag: ${{ matrix.imageTag }}
      dockerFileContext: ${{ matrix.context }}
      signImage: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
      DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
      DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

  build-gradle-android-images:
    name: "Build Gradle Android Images"
    needs: build-gradle-images
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageTag: jdk8-gradle4-android
            context: gradle/jdk8-gradle4-android
          - imageTag: jdk8-gradle6-android
            context: gradle/jdk8-gradle6-android
          - imageTag: jdk17-gradle8-android
            context: gradle/jdk17-gradle8-android
    
    uses: exoplatform/swf-scripts/.github/workflows/buildDockerImage.yml@master
    with:
      dockerImage: "exoplatform/ci"
      dockerImageTag: ${{ matrix.imageTag }}
      dockerFileContext: ${{ matrix.context }}
      signImage: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PRIVATE_KEY_ID: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
      DOCKER_PRIVATE_KEY: ${{ secrets.DOCKER_PRIVATE_KEY }}
      DOCKER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}